driver-class-name: "com.mysql.cj.jdbc.Driver"
auth-database-url: "jdbc:mysql://localhost:3306/multilogin"
auth-database-username: "root"
auth-database-password: "root"
skin-database-url: "jdbc:mysql://localhost:3306/blessingskin"
skin-database-username: "root"
skin-database-password: "root"
file-path: "/blessingskin/storage/textures"
remote-url: "https://sessionserver.mojang.com/session/minecraft/profile/{UUID}"
